import { createRouter, createWebHistory } from 'vue-router'
import { useAuthStore } from '../stores/auth.js'

const routes = [
  {
    path: '/login',
    name: 'Login',
    component: () => import('../views/LoginView.vue'),
    meta: { public: true }
  },
  {
    path: '/',
    component: () => import('../layouts/AdminLayout.vue'),
    meta: { requiresAuth: true },
    children: [
      { path: '',        redirect: '/dashboard' },
      { path: 'dashboard',    name: 'Dashboard',   component: () => import('../views/DashboardView.vue') },
      { path: 'pages',        name: 'Pages',       component: () => import('../views/PagesView.vue') },
      { path: 'pages/new',    name: 'PageNew',     component: () => import('../views/PageEditView.vue') },
      { path: 'pages/:id',    name: 'PageEdit',    component: () => import('../views/PageEditView.vue') },
      { path: 'posts',        name: 'Posts',       component: () => import('../views/PostsView.vue') },
      { path: 'posts/new',    name: 'PostNew',     component: () => import('../views/PostEditView.vue') },
      { path: 'posts/:id',    name: 'PostEdit',    component: () => import('../views/PostEditView.vue') },
      { path: 'media',        name: 'Media',       component: () => import('../views/MediaView.vue') },
      { path: 'navigation',   name: 'Navigation',  component: () => import('../views/NavigationView.vue') },
      { path: 'orders',           name: 'Orders',       component: () => import('../views/OrdersView.vue') },
      { path: 'orders/kanban',    name: 'OrderKanban',  component: () => import('../views/OrderKanbanView.vue') },
      { path: 'fulfillment',      name: 'Fulfillment',  component: () => import('../views/FulfillmentView.vue') },
      { path: 'coupons',          name: 'Coupons',      component: () => import('../views/CouponsView.vue') },
      { path: 'coupon-analytics', name: 'CouponAnalytics', component: () => import('../views/CouponAnalyticsView.vue') },
      { path: 'import-history',   name: 'ImportHistory',   component: () => import('../views/ImportHistoryView.vue') },
      { path: 'products',         name: 'Products',     component: () => import('../views/ProductsView.vue') },
      { path: 'products/new',     name: 'ProductNew',   component: () => import('../views/ProductEditView.vue') },
      { path: 'products/:id',     name: 'ProductEdit',  component: () => import('../views/ProductEditView.vue') },
      { path: 'events',           name: 'Events',       component: () => import('../views/EventsView.vue') },
      { path: 'events/new',       name: 'EventNew',     component: () => import('../views/EventEditView.vue') },
      { path: 'events/:id',       name: 'EventEdit',    component: () => import('../views/EventEditView.vue') },
      { path: 'comments',     name: 'Comments',    component: () => import('../views/CommentsView.vue') },
      { path: 'contact',      name: 'Contact',     component: () => import('../views/ContactView.vue') },
      { path: 'users',        name: 'Users',       component: () => import('../views/UsersView.vue') },
      { path: 'analytics',    name: 'Analytics',   component: () => import('../views/AnalyticsView.vue') },
      { path: 'redirects',    name: 'Redirects',   component: () => import('../views/RedirectsView.vue') },
      { path: 'newsletter',   name: 'Newsletter',  component: () => import('../views/NewsletterView.vue') },
      { path: 'newsletter-templates', name: 'NewsletterTemplates', component: () => import('../views/NewsletterTemplatesView.vue') },
      { path: 'backup',       name: 'Backup',      component: () => import('../views/BackupView.vue') },
      { path: 'tags',         name: 'Tags',        component: () => import('../views/TagsView.vue') },
      { path: 'forms',        name: 'Forms',       component: () => import('../views/FormsView.vue') },
      { path: 'forms/new',    name: 'FormNew',     component: () => import('../views/FormEditView.vue') },
      { path: 'forms/:id',    name: 'FormEdit',    component: () => import('../views/FormEditView.vue') },
      { path: 'forms/:id/submissions', name: 'FormSubmissions', component: () => import('../views/FormSubmissionsView.vue') },
      { path: 'webhooks',         name: 'Webhooks',       component: () => import('../views/WebhooksView.vue') },
      { path: 'notifications',    name: 'Notifications',  component: () => import('../views/NotificationsView.vue') },
      { path: 'api-keys',         name: 'ApiKeys',        component: () => import('../views/ApiKeysView.vue') },
      { path: 'reviews',          name: 'Reviews',        component: () => import('../views/ReviewsView.vue') },
      { path: 'customers',        name: 'Customers',      component: () => import('../views/CustomersView.vue') },
      { path: 'shipping',         name: 'Shipping',       component: () => import('../views/ShippingView.vue') },
      { path: 'abandoned-carts',  name: 'AbandonedCarts', component: () => import('../views/AbandonedCartsView.vue') },
      { path: 'homepage',          name: 'Homepage',       component: () => import('../views/HomepageBuilderView.vue') },
      { path: 'tax-rates',        name: 'TaxRates',       component: () => import('../views/TaxRatesView.vue') },
      { path: 'gift-cards',       name: 'GiftCards',      component: () => import('../views/GiftCardsView.vue') },
      { path: 'downloads',        name: 'Downloads',      component: () => import('../views/DownloadsView.vue') },
      { path: 'activity-log',     name: 'ActivityLog',    component: () => import('../views/ActivityLogView.vue') },
      { path: 'subscriptions',    name: 'Subscriptions',  component: () => import('../views/SubscriptionsView.vue') },
      { path: 'revenue',          name: 'Revenue',        component: () => import('../views/RevenueView.vue') },
      { path: 'affiliates',       name: 'Affiliates',     component: () => import('../views/AffiliatesView.vue') },
      { path: 'inventory',        name: 'Inventory',      component: () => import('../views/InventoryView.vue') },
      { path: 'currency',         name: 'Currency',       component: () => import('../views/CurrencyView.vue') },
      { path: 'bundles',          name: 'Bundles',        component: () => import('../views/BundlesView.vue') },
      { path: 'bundles/:id',      name: 'BundleEdit',     component: () => import('../views/BundleEditView.vue') },
      { path: 'product-qa',       name: 'ProductQA',      component: () => import('../views/ProductQAView.vue') },
      { path: 'import',           name: 'Import',         component: () => import('../views/ImportView.vue') },
      { path: 'stock-alerts',     name: 'StockAlerts',    component: () => import('../views/StockAlertsView.vue') },
      { path: 'stock-import',     name: 'StockImport',    component: () => import('../views/StockImportView.vue') },
      { path: 'scheduled-queue',  name: 'ScheduledQueue', component: () => import('../views/ScheduledQueueView.vue') },
      { path: 'returns',          name: 'Returns',        component: () => import('../views/ReturnsView.vue') },
      { path: 'email-templates',  name: 'EmailTemplates', component: () => import('../views/EmailTemplatesView.vue') },
      { path: 'flash-sales',      name: 'FlashSales',     component: () => import('../views/FlashSalesView.vue') },
      { path: 'announcement-bars', name: 'AnnouncementBars', component: () => import('../views/AnnouncementBarsView.vue') },
      { path: 'popups',           name: 'Popups',         component: () => import('../views/PopupsView.vue') },
      { path: 'support',          name: 'Support',        component: () => import('../views/SupportView.vue') },
      { path: 'content-calendar', name: 'ContentCalendar', component: () => import('../views/ContentCalendarView.vue') },
      { path: 'site-health',      name: 'SiteHealth',     component: () => import('../views/SiteHealthView.vue') },
      { path: 'ab-testing',         name: 'AbTesting',        component: () => import('../views/AbTestingView.vue') },
      { path: 'search-analytics',  name: 'SearchAnalytics',  component: () => import('../views/SearchAnalyticsView.vue') },
      { path: 'email-sequences',   name: 'EmailSequences',   component: () => import('../views/EmailSequencesView.vue') },
      { path: 'customer-segments', name: 'CustomerSegments', component: () => import('../views/CustomerSegmentsView.vue') },
      { path: 'languages',         name: 'Languages',        component: () => import('../views/LanguagesView.vue') },
      { path: 'store-locator',     name: 'StoreLocator',     component: () => import('../views/StoreLocatorView.vue') },
      { path: 'performance',       name: 'Performance',      component: () => import('../views/PerformanceView.vue') },
      { path: 'digest',            name: 'Digest',           component: () => import('../views/DigestView.vue') },
      { path: 'push-notifications', name: 'PushNotifications', component: () => import('../views/PushNotificationsView.vue') },
      { path: 'price-alerts',      name: 'PriceAlerts',      component: () => import('../views/PriceAlertsView.vue') },
      { path: 'product-badges',    name: 'ProductBadges',    component: () => import('../views/ProductBadgesView.vue') },
      { path: 'social-proof',      name: 'SocialProof',      component: () => import('../views/SocialProofView.vue') },
      { path: 'store-credit',      name: 'StoreCredit',      component: () => import('../views/StoreCreditView.vue') },
      { path: 'referral',          name: 'Referral',         component: () => import('../views/ReferralView.vue') },
      { path: 'collections',       name: 'Collections',      component: () => import('../views/CollectionsView.vue') },
      { path: 'upsell',            name: 'Upsell',           component: () => import('../views/UpsellView.vue') },
      { path: 'suppliers',         name: 'Suppliers',        component: () => import('../views/SuppliersView.vue') },
      { path: 'waitlist',          name: 'Waitlist',         component: () => import('../views/WaitlistView.vue') },
      { path: 'customer-groups',   name: 'CustomerGroups',   component: () => import('../views/CustomerGroupsView.vue') },
      { path: 'stock-forecast',     name: 'StockForecast',     component: () => import('../views/StockForecastView.vue') },
      { path: 'inventory-locations', name: 'InventoryLocations', component: () => import('../views/InventoryLocationsView.vue') },
      { path: 'order-bumps',        name: 'OrderBumps',        component: () => import('../views/OrderBumpsView.vue') },
      { path: 'review-requests',    name: 'ReviewRequests',    component: () => import('../views/ReviewRequestsView.vue') },
      { path: 'loyalty-tiers',      name: 'LoyaltyTiers',      component: () => import('../views/LoyaltyTiersView.vue') },
      { path: 'product-subscriptions', name: 'ProductSubscriptions', component: () => import('../views/ProductSubscriptionsView.vue') },
      { path: 'storefront-customizer', name: 'StorefrontCustomizer', component: () => import('../views/StorefrontCustomizerView.vue') },
      { path: 'bookings',          name: 'Bookings',          component: () => import('../views/BookingsView.vue') },
      { path: 'automation',        name: 'Automation',        component: () => import('../views/AutomationView.vue') },
      { path: 'coupon-campaigns',  name: 'CouponCampaigns',   component: () => import('../views/CouponCampaignsView.vue') },
      { path: 'sms',               name: 'Sms',              component: () => import('../views/SmsView.vue') },
      { path: 'gift-registry',     name: 'GiftRegistry',     component: () => import('../views/GiftRegistryView.vue') },
      { path: 'auto-discounts',    name: 'AutoDiscounts',    component: () => import('../views/AutoDiscountsView.vue') },
      { path: 'customer-ltv',          name: 'CustomerLtv',          component: () => import('../views/CustomerLtvView.vue') },
      { path: 'order-tags',            name: 'OrderTags',            component: () => import('../views/OrderTagsView.vue') },
      { path: 'inventory-adjustments', name: 'InventoryAdjustments', component: () => import('../views/InventoryAdjustmentsView.vue') },
      { path: 'tax-report',            name: 'TaxReport',            component: () => import('../views/TaxReportView.vue') },
      { path: 'vendors',           name: 'Vendors',          component: () => import('../views/VendorsView.vue') },
      { path: 'charity',           name: 'Charity',          component: () => import('../views/CharityView.vue') },
      { path: 'changelog',         name: 'Changelog',        component: () => import('../views/ChangelogView.vue') },
      { path: 'nps',               name: 'Nps',              component: () => import('../views/NpsView.vue') },
      { path: 'geo-analytics',     name: 'GeoAnalytics',     component: () => import('../views/GeoAnalyticsView.vue') },
      { path: 'scheduled-reports', name: 'ScheduledReports', component: () => import('../views/ScheduledReportsView.vue') },
      { path: 'stock-history',     name: 'StockHistory',     component: () => import('../views/StockHistoryView.vue') },
      { path: 'preorders',         name: 'Preorders',        component: () => import('../views/PreordersView.vue') },
      { path: 'order-shipments',   name: 'OrderShipments',   component: () => import('../views/OrderShipmentsView.vue') },
      { path: 'ai-content',        name: 'AiContent',        component: () => import('../views/AiContentView.vue') },
      { path: 'recommendations',    name: 'Recommendations',  component: () => import('../views/RecommendationsView.vue') },
      { path: 'customer-import',    name: 'CustomerImport',   component: () => import('../views/CustomerImportView.vue') },
      { path: 'order-analytics',    name: 'OrderAnalytics',   component: () => import('../views/OrderAnalyticsView.vue') },
      { path: 'surveys',            name: 'Surveys',          component: () => import('../views/SurveysView.vue') },
      { path: 'customer-tags',     name: 'CustomerTags',     component: () => import('../views/CustomerTagsView.vue') },
      { path: 'order-statuses',    name: 'OrderStatuses',    component: () => import('../views/OrderStatusesView.vue') },
      { path: 'ip-blocklist',      name: 'IpBlocklist',      component: () => import('../views/IpBlocklistView.vue') },
      { path: 'site-audit',        name: 'SiteAudit',        component: () => import('../views/SiteAuditView.vue') },
      { path: 'media-alt',         name: 'MediaAlt',         component: () => import('../views/MediaAltView.vue') },
      { path: 'error-logs',        name: 'ErrorLogs',        component: () => import('../views/ErrorLogsView.vue') },
      { path: 'bulk-price',        name: 'BulkPrice',        component: () => import('../views/BulkPriceView.vue') },
      { path: 'customer-timeline', name: 'CustomerTimeline', component: () => import('../views/CustomerTimelineView.vue') },
      { path: 'cookie-consent',    name: 'CookieConsent',    component: () => import('../views/CookieConsentView.vue') },
      { path: 'funnel',            name: 'Funnel',           component: () => import('../views/FunnelView.vue') },
      { path: 'heatmap',           name: 'Heatmap',          component: () => import('../views/HeatmapView.vue') },
      { path: 'live-chat',         name: 'LiveChat',         component: () => import('../views/LiveChatView.vue') },
      { path: 'loyalty-rewards',   name: 'LoyaltyRewards',   component: () => import('../views/LoyaltyRewardsView.vue') },
      { path: 'custom-404',        name: 'Custom404',        component: () => import('../views/Custom404View.vue') },
      { path: 'knowledge-base',    name: 'KnowledgeBase',    component: () => import('../views/KnowledgeBaseView.vue') },
      { path: 'knowledge-base/new', name: 'KbArticleNew',   component: () => import('../views/KbArticleEditView.vue') },
      { path: 'knowledge-base/:id/edit', name: 'KbArticleEdit', component: () => import('../views/KbArticleEditView.vue') },
      { path: 'social-scheduler',  name: 'SocialScheduler',  component: () => import('../views/SocialSchedulerView.vue') },
      { path: 'canned-responses',  name: 'CannedResponses',  component: () => import('../views/CannedResponsesView.vue') },
      { path: 'team',              name: 'Team',             component: () => import('../views/TeamView.vue') },
      { path: 'reporting-hub',      name: 'ReportingHub',     component: () => import('../views/ReportingHubView.vue') },
      { path: 'csat',              name: 'Csat',             component: () => import('../views/CsatView.vue') },
      { path: 'gdpr',              name: 'Gdpr',             component: () => import('../views/GdprView.vue') },
      { path: 'winback',           name: 'Winback',          component: () => import('../views/WinbackView.vue') },
      { path: 'customer-journey',  name: 'CustomerJourney',  component: () => import('../views/CustomerJourneyView.vue') },
      { path: 'quote-requests',    name: 'QuoteRequests',    component: () => import('../views/QuoteRequestsView.vue') },
      { path: 'price-history',     name: 'PriceHistory',     component: () => import('../views/PriceHistoryView.vue') },
      { path: 'batch-fulfill',     name: 'BatchFulfill',     component: () => import('../views/BatchFulfillView.vue') },
      { path: 'disputes',          name: 'Disputes',         component: () => import('../views/DisputesView.vue') },
      { path: 'feedback',          name: 'Feedback',         component: () => import('../views/FeedbackView.vue') },
      { path: 'reorder',           name: 'Reorder',          component: () => import('../views/ReorderView.vue') },
      { path: 'product-labels',    name: 'ProductLabels',    component: () => import('../views/ProductLabelsView.vue') },
      { path: 'margin',            name: 'Margin',           component: () => import('../views/MarginView.vue') },
      { path: 'import-history',    name: 'ImportHistory',    component: () => import('../views/ImportHistoryView.vue') },
      { path: 'orders/kanban',     name: 'OrderKanban',      component: () => import('../views/OrderKanbanView.vue') },
      { path: 'coupon-analytics',  name: 'CouponAnalytics',  component: () => import('../views/CouponAnalyticsView.vue') },
      { path: 'unified-inbox',     name: 'UnifiedInbox',     component: () => import('../views/UnifiedInboxView.vue') },
      { path: 'translations',      name: 'Translations',     component: () => import('../views/TranslationsView.vue') },
      { path: 'barcodes',          name: 'Barcodes',         component: () => import('../views/BarcodesView.vue') },
      { path: 'social-calendar',   name: 'SocialCalendar',   component: () => import('../views/SocialCalendarView.vue') },
      { path: 'settings',          name: 'Settings',         component: () => import('../views/SettingsView.vue') },
    ]
  },
  { path: '/:pathMatch(.*)*', redirect: '/' }
]

const router = createRouter({
  history: createWebHistory(),
  routes
})

router.beforeEach(async (to) => {
  const auth = useAuthStore()
  if (to.meta.requiresAuth && !auth.isLoggedIn) {
    return { name: 'Login' }
  }
  if (to.name === 'Login' && auth.isLoggedIn) {
    return { name: 'Dashboard' }
  }
})

export default router
